services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  # mysql:
  #   image: mysql:8.0.30-debian
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: test
  #   volumes:
  #     - ./mysql-data:/var/lib/mysql